local BrainrotModels = {
	"1x1x1x1",
	"Agarrini La Pallini",
	"Avocadini Guffo",
	"Ballerina Cappuccina",
	"Ballerino Lololo",
	"Bambini Crostini",
	"Banana Dancana",
	"Bananini Kittini",
	"Bananita Dolphinita",
	"Blueberrinni Octopusini",
	"Bobrito Bandito",
	"Bombardiro Crocodilo",
	"Bombombini Gusini",
	"Boneca Ambalabu",
	"Brr Brr Patapim",
	"Brri Brri Bicus Dicus",
	"Burbaloni Luliloli",
	"Cachorrito Melonito",
	"Cacto Hipopotamo",
	"Cappuccino Assassino",
	"Cavallo Virtuoso",
	"Chef Crabracadabra",
	"Chicleteira Bicicleteira",
	"Chicleteirina Bicicleteirina",
	"Chillin Chili",
	"Chimpanzini Bananini",
	"Cocofanto Elefanto",
	"Dragon Cannelloni",
	"Esok Sekolah",
	"Espresso Signora",
	"Fluri Flura",
	"Frigo Camelo",
	"Ganganzelli Trulala",
	"Gangster Footera",
	"Garamararam",
	"Girafa Celeste",
	"Glorbo Fruttodrillo",
	"Gorillo Watermelondrillo",
	"Illuminato Triangolo",
	"Job Job Job Sahur",
	"Karkerkar Kurkur",
	"La Grande Combinasion",
	"La Vacca Saturno Saturnita",
	"Lerulerulerule",
	"Lionel Cactuseli",
	"Lirili Larila",
	"Los Tralaleritos",
	"Madudung",
	"Matteo",
	"Meowl",
	"Noo My Examen",
	"Nyannini Cattalini",
	"Odin Din Din Dun",
	"Orangutini Ananassini",
	"Orcalero Orcala",
	"Pakrahmatmamat",
	"Pakrahmatmatina",
	"Pandaccini Bananini",
	"Pipi Kiwi",
	"Pipi Potato",
	"Pot Hotspot",
	"Quesadilla Crocodila",
	"Rhino Toasterino",
	"Six Seven",
	"Smurfo Gatto",
	"Strawberrelli Flamingelli",
	"Strawberry Elephant",
	"Svinina Bombardino",
	"Swag Soda",
	"Ta Ta Ta Ta Sahur",
	"Talpa Di Fero",
	"Tigroligre Frutonni",
	"Tim Cheese",
	"Tirilikalika Tirilikalako",
	"Torrtuginni Dragonfrutini",
	"Tralaledon",
	"Tralalero Tralala",
	"Tralalita Tralala",
	"Tric Trac Barabum",
	"Triplito Tralaleritos",
	"Trippi Troppi",
	"Trippi Troppi Troppa Trippa",
	"Trulimero Trulicina",
	"Tung Sahur",
	"W Or L",
	"Yess My Examen",
	"Zibra Zubra Zibralini",
}

return BrainrotModels